name: minions-bundles-execution-workspace
description: Granular task management and daily tracking bundle — sprints, tasks, blockers
tier: idea
lane: minions
priority: medium
oss: true
stack: [typescript]
repo: "https://github.com/mxn2020/minions-bundles-execution"
deploy_url: null
last_active: 2026-02-25
tags: []
notes: 
